author: [MinecraftDawn,Zhuowei]
database: false
description: Implementation of the Minecraft PI modding API
main: com.minecraftdawn.raspberryjuice.RaspberryJuicePlugin
name: RaspberryJuice
startup: postworld
version: '1.14-0.4'
api-version: 1.13